# **Import Requirements**

In [251]:
import pandas as pd
import numpy as np
import joblib 
from sklearn.preprocessing import StandardScaler

In [252]:
df = pd.read_csv("../data/processed/credit_card_fe.csv")

In [253]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8950 entries, 0 to 8949
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   balance                           8950 non-null   float64
 1   balance_frequency                 8950 non-null   float64
 2   purchases                         8950 non-null   float64
 3   cash_advance                      8950 non-null   float64
 4   oneoff_purchases_frequency        8950 non-null   float64
 5   purchases_installments_frequency  8950 non-null   float64
 6   cash_advance_frequency            8950 non-null   float64
 7   credit_limit                      8950 non-null   float64
 8   payments                          8950 non-null   float64
 9   minimum_payments                  8950 non-null   float64
 10  prc_full_payment                  8950 non-null   float64
 11  tenure                            8950 non-null   int64
 12  credit_utilization                8950 non-null   float64
 13  payment_ratio                     8950 non-null   float64
dtypes: float64(13), int64(1)
memory usage: 979.0 KB

In [254]:
df.sample(5)

,balance,balance_frequency,purchases,cash_advance,oneoff_purchases_frequency,purchases_installments_frequency,cash_advance_frequency,credit_limit,payments,minimum_payments,prc_full_payment,tenure,credit_utilization,payment_ratio
788,2302.479845,1.000000,0.00,861.574218,0.000000,0.000000,0.750000,2600.0,0.000000,308.017569,0.000000,12,0.885569,0.000000
103,0.624240,0.090909,389.96,0.000000,0.000000,1.000000,0.000000,4500.0,0.000000,308.017569,0.000000,12,0.000139,0.000000
7091,679.508597,1.000000,380.10,0.000000,0.000000,0.416667,0.000000,2500.0,443.106331,249.318198,0.000000,12,0.271803,1.777272
2084,1109.911791,1.000000,3150.00,0.000000,0.083333,1.000000,0.000000,2500.0,2694.972436,431.443631,0.083333,12,0.443965,6.246407
7849,1091.973832,1.000000,0.00,77.349474,0.000000,0.000000,0.083333,1200.0,259.506889,518.930756,0.000000,12,0.909978,0.500080

In [255]:
print("Jumlah data duplikat:", df.duplicated().sum())

Jumlah data duplikat: 0

In [256]:
df.isna().sum()

balance                             0
balance_frequency                   0
purchases                           0
cash_advance                        0
oneoff_purchases_frequency          0
purchases_installments_frequency    0
cash_advance_frequency              0
credit_limit                        0
payments                            0
minimum_payments                    0
prc_full_payment                    0
tenure                              0
credit_utilization                  0
payment_ratio                       0
dtype: int64

In [257]:
np.isinf(df).sum()

balance                             0
balance_frequency                   0
purchases                           0
cash_advance                        0
oneoff_purchases_frequency          0
purchases_installments_frequency    0
cash_advance_frequency              0
credit_limit                        0
payments                            0
minimum_payments                    0
prc_full_payment                    0
tenure                              0
credit_utilization                  0
payment_ratio                       0
dtype: int64

In [258]:
negatif = (df.select_dtypes(include="number") < 0).any().any()

print("Ada nilai negatif:", negatif)

Ada nilai negatif: False

# **Cek Skewness**

In [259]:
skewness = df.skew().sort_values(ascending=False)
skewness

minimum_payments                    13.841597
purchases                            8.144269
payments                             5.907620
cash_advance                         5.166609
payment_ratio                        3.233821
balance                              2.393386
prc_full_payment                     1.942820
cash_advance_frequency               1.828686
oneoff_purchases_frequency           1.535613
credit_limit                         1.522636
purchases_installments_frequency     0.509201
credit_utilization                   0.464585
balance_frequency                   -2.023266
tenure                              -2.943017
dtype: float64

In [260]:
check = ['credit_limit', 'prc_full_payment','cash_advance_frequency', 'oneoff_purchases_frequency']

pd.DataFrame({
    'skew_sebelum': df[check].skew(),
    'skew_setelah_log1p': np.log1p(df[check]).skew()
})

                            skew_sebelum  skew_setelah_log1p
credit_limit                    1.522636           -0.101408
prc_full_payment                1.942820            1.746046
cash_advance_frequency          1.828686            1.455462
oneoff_purchases_frequency      1.535613            1.290617

Di antara fitur yang memiliki skewness di rentang 1 hingga 1.9, angka skew credit_limit turun yang cukup jauh setelah dilog dibandingkan fitur lainnya. Oleh sebab itu, **credit_limit** akan masuk dimasukkan dalam list fitur yang akan dilog.

# **Log**

In [261]:
log_features = [
    'minimum_payments',
    'purchases',
    'payments',
    'cash_advance',
    'balance',
    'payment_ratio',
    'credit_limit'
]

for col in log_features:
  df[col] = np.log1p(df[col])

In [262]:
skewness_after = df.skew().sort_values(ascending=False)
skewness_after

prc_full_payment                    1.942820
cash_advance_frequency              1.828686
oneoff_purchases_frequency          1.535613
payment_ratio                       0.804900
purchases_installments_frequency    0.509201
credit_utilization                  0.464585
cash_advance                        0.262594
credit_limit                       -0.101408
minimum_payments                   -0.489385
purchases                          -0.764492
balance                            -0.861021
payments                           -1.778312
balance_frequency                  -2.023266
tenure                             -2.943017
dtype: float64

# **Scaling**

In [ ]:
X = df.copy()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
df_scaled = pd.DataFrame(
    X_scaled,
    columns=X.columns,
    index=X.index
)

df_scaled.head(5)

,balance,balance_frequency,purchases,cash_advance,oneoff_purchases_frequency,purchases_installments_frequency,cash_advance_frequency,credit_limit,payments,minimum_payments,prc_full_payment,tenure,credit_utilization,payment_ratio
0,-1.205218,-0.249434,-0.113532,-0.930733,-0.678661,-0.707313,-0.675349,-1.447163,-0.824484,-0.717276,-0.525551,0.36068,-0.981732,-0.510343
1,0.948918,0.134325,-1.679855,1.528788,-0.678661,-0.916995,0.573963,0.926060,1.065033,0.862946,0.234227,0.36068,0.200202,0.233167
2,0.824993,0.518084,0.600727,-0.930733,2.673451,-0.916995,-0.675349,1.010229,-0.119300,0.446732,-0.525551,0.36068,-0.153897,-0.735433
3,0.624653,-1.016953,0.827499,0.564372,-0.399319,-0.916995,-0.258913,1.010229,-4.161996,-0.104757,-0.525551,0.36068,-0.467298,-1.489419
4,0.271260,0.518084,-0.708481,-0.930733,-0.399319,-0.916995,-0.675349,-1.224909,-0.064979,-0.282668,-0.525551,0.36068,0.835530,-0.036819

In [265]:
df_scaled.describe().T
df_scaled.describe().T[['mean','std']]

                                          mean       std
balance                           1.270244e-17  1.000056
balance_frequency                 2.286439e-16  1.000056
purchases                         6.986342e-17  1.000056
cash_advance                      5.716098e-17  1.000056
oneoff_purchases_frequency       -8.891708e-17  1.000056
purchases_installments_frequency  4.604634e-17  1.000056
cash_advance_frequency            5.557317e-17  1.000056
credit_limit                     -5.335025e-16  1.000056
payments                          3.556683e-16  1.000056
minimum_payments                 -1.270244e-16  1.000056
prc_full_payment                  0.000000e+00  1.000056
tenure                            2.794537e-16  1.000056
credit_utilization               -5.080976e-17  1.000056
payment_ratio                     3.493171e-17  1.000056

# **Save Dataset**

In [266]:
df_scaled.to_csv('../data/processed/credit_card_scaled.csv', index=False)
df.to_csv('../data/processed/credit_card_preprocessed.csv', index=False)
joblib.dump(scaler, '../models/scaler.pkl')

['../models/scaler.pkl']